#' @title table genes and snps
#' @description creates a 2xn table with genes in the first
#' column and the associated snps in the second column.
#' @param snpgene a list named by genes containing snps, i.e. the result generated by snpToGene
#' @author flassen
#' @export
#' @examples \dontrun{geneTable(snpToGene('rs142920272'))}

geneTable <- function(snpgene, outfile = NULL, delim = ';'){

  dat = lapply(snpgene, function(x) paste(x, collapse = delim))
  df = data.frame(geneName = names(dat), snps = unlist(dat))
  row.names(df) <- NULL
  if (!is.null(outfile)) write.csv(df, outfile)
  return(df)
}

